from collections.abc import Callable
from typing import Protocol

from ...models import (AssistantRequest, AssistantResponse, IncidentDiagnosis,
                       LineageFact, MemoryRecord, OperationalAction,
                       PipelineProposal, PlatformSnapshot,
                       RecommendationFeedback, SourceAssessment)


class AssessmentReader(Protocol):
    def get_assessment(self, assessment_id: str) -> SourceAssessment: ...


class ProposalRepository(Protocol):
    def get_pipeline_proposal(self, proposal_id: str) -> PipelineProposal: ...
    def save_pipeline_proposal(self, build: Callable[[int], PipelineProposal], assessment_id: str | None, actor: str) -> PipelineProposal: ...


class OperationalActionStore(Protocol):
    """Durable approval state; `update` must only apply when the stored status still matches."""

    def insert(self, action: OperationalAction) -> None: ...
    def get(self, action_id: str) -> OperationalAction | None: ...
    def find_by_idempotency_key(self, idempotency_key: str) -> OperationalAction | None: ...
    def token_hash(self, action_id: str) -> str | None: ...
    def update(self, action: OperationalAction, expected_status: str, token_hash: str | None = None, idempotency_key: str | None = None) -> OperationalAction | None: ...


class IntelligenceStore(Protocol):
    def add_incident(self, diagnosis: IncidentDiagnosis) -> None: ...
    def incidents_for_deployment(self, deployment_id: str) -> list[IncidentDiagnosis]: ...
    def open_incidents(self) -> list[IncidentDiagnosis]: ...
    def add_memory(self, record: MemoryRecord) -> None: ...
    def search_memory(self, terms: list[str], scope: str | None) -> list[MemoryRecord]: ...
    def add_feedback(self, item: RecommendationFeedback) -> None: ...
    def feedback_totals(self) -> tuple[int, int, int]: ...


class PlatformReader(Protocol):
    def platform_snapshot(self) -> PlatformSnapshot: ...
    def lineage_facts(self) -> list[LineageFact]: ...


class AssistantRepository(Protocol):
    def assistant_context(self, assessment_id: str | None = None, deployment_id: str | None = None) -> dict: ...
    def save_assistant_exchange(self, request: AssistantRequest, response: AssistantResponse, actor: str) -> AssistantResponse: ...

